# Data Prep

Uma das coisas mais importantes em modelagem/machine learning é a preparação dos dados. Por esse motivo, sempre vale a pena gastar um tempinho para sair da inércia em algumas ferramentas que serão úteis. Outras coisas mais legais serão descobertas com o passar do tempo, à medida que novos conjuntos de dados forem sendo usados em diferetes propóstivos.

Baseado em: github.com/clumdee/Python-for-Finance

## NumPy

Uma das bibliotecas mais importantes no Python, oferece diversas facilidades em programação numérica.

**Importe NumPy com a alias np**

**Crie um array com 10 zeros**

**Crie um array com 10 uns**

**Crie um array com 10 cincos**

**Crie um array de inteiros começando em 10 e terminando em 50**

**Crie um array com todos os números pares inteiros de 10 a 50**

**Crie uma matriz 3x3 com valores de 0 a 8**

**Crie uma matriz identidade 3x3**

**Gere um número aleatório entre 0 e 1**

**Gere um array com 25 números aleatórios amostrados de uma distribuição normal**

**Crie uma matriz começando em 0.01 e terminando em 1.0, com passo de 0.01**.

**Crie um array com 20 pontos linearmente espaçacos entre 0 e 1**

**Utilizar a seguinte matriz (mat) para replicar os resultados a seguir''**

In [2]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

20

array([[ 2],
       [ 7],
       [12]])

array([21, 22, 23, 24, 25])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Ainda com a matriz mat, calcule a soma de todos os valores**

**Ainda com a matriz mat, calcule o desvio padrão**

**Ainda com a matriz mat, calcule a soma de cada coluna**

## Pandas

Outra biblioteca super importante, trás o conceito de Data Frames. Apresenta várias facilidades em Data Prep, sendo seu formato aceito por padrão em diversos pacotes de machine learning.

*Tentar realizar todos os exercícios de Pandas em apenas uma linha.*

**Importar Pandas com o alias pd**

**Importar arquivo banks**

**Checar as primeiras linhas do data frame**

**Checar os nomes de todas as colunas**

**Checar quantos estados (ST) existem no data frame**

**Checar quais estados (ST) existem no data frame**

**Verificar quais são os 5 estados com maior quantidade de bancos falidos**

**Verificar quais são as instituições que mas compram bancos (acquiring institutions)**

**Quantos bancos o State Bank of Texas adquiriu? Quantos eram realmente no Texas?**

**Qual a cidade na Californa tem mais bancos falidos?**

**Quantos bancos não possuem a palavra "Bank" e em seus nomes?**

**Quantos bancos possuem nome começando com a letra "s"?**

**Quantos valores CERT são acima de 20000?**

**Quantos bancos possuem nomes que consistem de exatamente duas palavras? (ex: "First Bank", "Bank Georgia")**

**Quantos bancos fecharam no ano de 2008?**