Leia as 5 primeiras linhas do dataset iris e calcule a distância de Minkowski com p = 2 entre cada instância, mostrando o resultado no formato de matriz.

*Dica: scipy.spatial*

In [16]:
import pandas as pd
import numpy as np

from scipy.spatial import minkowski_distance

In [30]:
iris = pd.read_csv('datasets/iris.csv')

iris_5 = iris.iloc[:5, 1:5].values

distancia = np.zeros(25).reshape(-1, 5)

for lin in range(5):
    for col in range(5):
        distancia[lin, col] = minkowski_distance(iris_5[lin], iris_5[col], p = 2)

distancia

array([[0.        , 0.53851648, 0.50990195, 0.64807407, 0.14142136],
       [0.53851648, 0.        , 0.3       , 0.33166248, 0.60827625],
       [0.50990195, 0.3       , 0.        , 0.24494897, 0.50990195],
       [0.64807407, 0.33166248, 0.24494897, 0.        , 0.64807407],
       [0.14142136, 0.60827625, 0.50990195, 0.64807407, 0.        ]])

Da mesma forma que no item anterior, calcule dessa vez a distância Euclidiana.

In [31]:
from scipy.spatial.distance import euclidean

distancia = np.zeros(25).reshape(-1, 5)

for lin in range(5):
    for col in range(5):
        distancia[lin, col] = euclidean(iris_5[lin], iris_5[col])

distancia

array([[0.        , 0.53851648, 0.50990195, 0.64807407, 0.14142136],
       [0.53851648, 0.        , 0.3       , 0.33166248, 0.60827625],
       [0.50990195, 0.3       , 0.        , 0.24494897, 0.50990195],
       [0.64807407, 0.33166248, 0.24494897, 0.        , 0.64807407],
       [0.14142136, 0.60827625, 0.50990195, 0.64807407, 0.        ]])

Multiplique todos os valores da primeira coluna por 1000 e, mais uma vez, calcule a matriz de distância Euclidiana.

In [32]:
iris_5[:, 0] = iris_5[:, 0] * 1000
iris_5

array([[5.1e+03, 3.5e+00, 1.4e+00, 2.0e-01],
       [4.9e+03, 3.0e+00, 1.4e+00, 2.0e-01],
       [4.7e+03, 3.2e+00, 1.3e+00, 2.0e-01],
       [4.6e+03, 3.1e+00, 1.5e+00, 2.0e-01],
       [5.0e+03, 3.6e+00, 1.4e+00, 2.0e-01]])

In [34]:
from scipy.spatial.distance import euclidean

distancia = np.zeros(25).reshape(-1, 5)

for lin in range(5):
    for col in range(5):
        distancia[lin, col] = round(euclidean(iris_5[lin], iris_5[col]), 2)

distancia

array([[  0., 200., 400., 500., 100.],
       [200.,   0., 200., 300., 100.],
       [400., 200.,   0., 100., 300.],
       [500., 300., 100.,   0., 400.],
       [100., 100., 300., 400.,   0.]])

O que pode ser feito para evitar problemas do tipo?

Utilizando o sklearn, utilize KNN com o método de validação Leave One Out, com a variável resposta sendo a coluna de espécies, e calcule a acurácia e do Gini para k = 3, 5 e 10. Pode ser necessário remover uma ou mais colunas do dataset.

Repita o item anterior, mudando o dataset para *ads* e usando a coluna *Purchased* como variável resposta. Pode ser necessário remover uma ou mais colunas do dataset.