# Introdução Ferramental

Uma das coisas mais importantes em modelagem/machine learning é a preparação dos dados. Por esse motivo, sempre vale a pena gastar um tempinho para sair da inércia em algumas ferramentas que serão úteis. Outras coisas mais legais serão descobertas com o passar do tempo, à medida que novos conjuntos de dados forem sendo usados em diferetes propóstivos.

Baseado em: github.com/clumdee/Python-for-Finance

## NumPy

Uma das bibliotecas mais importantes no Python, oferece diversas facilidades em programação numérica.

**Importe NumPy com a alias np**

In [1]:
import numpy as np

**Crie um array com 10 zeros**

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Crie um array com 10 uns**

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Crie um array com 10 cincos**

In [6]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Crie um array de inteiros começando em 10 e terminando em 50**

In [9]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Crie um array com todos os números pares inteiros de 10 a 50**

In [10]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Crie uma matriz 3x3 com valores de 0 a 8**

In [12]:
np.matrix(np.arange(0, 9)).reshape(3, 3)

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

**Crie uma matriz identidade 3x3**

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Gere um número aleatório entre 0 e 1**

In [21]:
np.random.rand()

0.4255821819946387

**Gere um array com 25 números aleatórios amostrados de uma distribuição normal**

In [23]:
np.random.normal(size = 25)

array([ 0.38654757, -0.60050014,  2.23763599,  1.41092813, -0.27502822,
        0.097358  ,  1.13320567, -0.71934989,  2.1676723 , -1.3094947 ,
       -1.49018415, -1.09034987, -1.56879361, -0.41745359,  0.37067025,
       -2.12325638,  0.79010782, -1.05214508, -0.43153048, -0.66157414,
       -0.76920547, -0.71731707, -1.15812736,  1.01291516, -1.09885264])

**Crie uma matriz começando em 0.01 e terminando em 1.0, com passo de 0.01**.

In [26]:
np.matrix(np.arange(0.01, 1.001, 0.01)).reshape(-1, 10)

matrix([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
        [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
        [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
        [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
        [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
        [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
        [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
        [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
        [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
        [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**Crie um array com 20 pontos linearmente espaçacos entre 0 e 1**

In [27]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

**Utilizar a seguinte matriz (mat) para replicar os resultados a seguir''**

In [28]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [32]:
mat[3, 4]

20

20

In [37]:
mat[:3, 1].reshape(-1, 1)

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [38]:
mat[-1, :]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [39]:
mat[-2:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Ainda com a matriz mat, calcule a soma de todos os valores**

In [40]:
mat.sum()

325

**Ainda com a matriz mat, calcule o desvio padrão**

In [42]:
mat.std()

7.211102550927978

**Ainda com a matriz mat, calcule a soma de cada coluna**

In [45]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

## Pandas

Outra biblioteca super importante, trás o conceito de Data Frames. Apresenta várias facilidades em Data Prep, sendo seu formato aceito por padrão em diversos pacotes de machine learning.

*Tentar realizar todos os exercícios de Pandas em apenas uma linha.*

**Importar Pandas com o alias pd**

In [46]:
import pandas as pd

**Importar arquivo banks**

In [49]:
df = pd.read_csv('datasets/banks.csv')

**Checar as primeiras linhas do data frame**

In [50]:
df.head()

Bank Name                City  ST  \
0                                Fayette County Bank          Saint Elmo  IL   
1  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee  WI   
2                                     First NBC Bank         New Orleans  LA   
3                                      Proficio Bank  Cottonwood Heights  UT   
4                      Seaway Bank and Trust Company             Chicago  IL   

    CERT                Acquiring Institution Closing Date Updated Date  
0   1802            United Fidelity Bank, fsb    26-May-17     1-Jun-17  
1  30003  First-Citizens Bank & Trust Company     5-May-17     1-Jun-17  
2  58302                         Whitney Bank    28-Apr-17    23-May-17  
3  35495                    Cache Valley Bank     3-Mar-17    18-May-17  
4  19328                  State Bank of Texas    27-Jan-17    18-May-17

**Checar os nomes de todas as colunas**

In [51]:
df.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

**Checar quantos estados (ST) existem no data frame**

In [52]:
df.ST.nunique()

44

**Checar quais estados (ST) existem no data frame**

In [54]:
df.ST.unique()

array(['IL', 'WI', 'LA', 'UT', 'NJ', 'AR', 'GA', 'PA', 'TN', 'WA', 'CO',
       'PR', 'FL', 'MN', 'CA', 'MD', 'OK', 'OH', 'SC', 'VA', 'ID', 'TX',
       'CT', 'AZ', 'NV', 'NC', 'KY', 'MO', 'KS', 'AL', 'MI', 'IN', 'IA',
       'NE', 'MS', 'NM', 'OR', 'NY', 'MA', 'SD', 'WY', 'WV', 'NH', 'HI'],
      dtype=object)

**Verificar quais são os 5 estados com maior quantidade de bancos falidos**

In [57]:
df.ST.value_counts().head()

GA    93
FL    75
IL    67
CA    41
MN    23
Name: ST, dtype: int64

**Verificar quais são as instituições que mas compram bancos (acquiring institutions)**

In [58]:
df['Acquiring Institution'].value_counts().head()

No Acquirer                            31
State Bank and Trust Company           12
First-Citizens Bank & Trust Company    11
Ameris Bank                            10
U.S. Bank N.A.                          9
Name: Acquiring Institution, dtype: int64

**Quantos bancos o State Bank of Texas adquiriu? Quantos eram realmente no Texas?**

In [59]:
len(df[df['Acquiring Institution'] == 'State Bank of Texas'])

3

**Qual a cidade na Californa tem mais bancos falidos?**

In [62]:
len(df[(df['Acquiring Institution'] == 'State Bank of Texas') & (df['ST'] == 'TX')])

1

**Quantos bancos não possuem a palavra "Bank" e em seus nomes?**

In [68]:
len(df[~df['Bank Name'].str.contains('Bank')])

14

**Quantos bancos possuem nome começando com a letra "s"?**

In [79]:
len(df[(df['Bank Name'].str[0] == 'S') | (df['Bank Name'].str[0] == 's')])

53

In [81]:
len(df[df['Bank Name'].str.startswith('S', 's')])

53

**Quantos valores CERT são acima de 20000?**

In [82]:
len(df[df['CERT'] > 20000])

417

**Quantos bancos possuem nomes que consistem de exatamente duas palavras? (ex: "First Bank", "Bank Georgia")**

In [83]:
len(df[df['Bank Name'].apply(lambda x: len(x.split())) == 2])

114

**Quantos bancos fecharam no ano de 2008?**

In [88]:
len(df[df['Closing Date'].apply(lambda x: x[-2:]) == '08'])

25